"""Video-level train/val/test splits over a manifest.

Splits are stratified by unified label and always operate at the clip
(video) level per ``docs/dataset_strategy.md``. Output lands in the existing
``datasets/splits/{train,val,test}.json`` placeholder schema so downstream
tooling can keep consuming the same files.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd
from sklearn.model_selection import train_test_split

from safewatch.data.manifest import MANIFEST_COLUMNS

logger = logging.getLogger("safewatch.data.split")

SPLIT_VERSION = "v0"
SPLIT_FILES = ("train.json", "val.json", "test.json")


@dataclass(frozen=True, slots=True)
class SplitResult:
    """Counts of a produced split, keyed by split name."""

    counts: dict[str, int]
    output_dir: Path

    @property
    def train(self) -> int:
        return self.counts["train"]

    @property
    def val(self) -> int:
        return self.counts["val"]

    @property
    def test(self) -> int:
        return self.counts["test"]


def split_manifest(
    manifest: pd.DataFrame,
    output_dir: Path,
    *,
    val_size: float = 0.15,
    test_size: float = 0.15,
    seed: int = 42,
) -> SplitResult:
    """Split ``manifest`` into train/val/test JSON files under ``output_dir``.

    Rows are stratified by ``label``; ``video_path`` must be unique. Raises a
    :class:`ValueError` with guidance when a class is too small to stratify.
    """

    required = {col for col in MANIFEST_COLUMNS}
    if not required.issubset(manifest.columns):
        missing = sorted(required - set(manifest.columns))
        raise ValueError(f"manifest missing required columns: {missing}")
    if len(manifest) < 2:
        raise ValueError("manifest needs at least two clips to split")
    if val_size <= 0 or test_size <= 0 or val_size + test_size >= 1.0:
        raise ValueError(
            "val_size and test_size must be > 0 and sum to < 1.0; "
            f"got val={val_size!r} test={test_size!r}"
        )
    duplicates = manifest["video_path"].duplicated()
    if bool(duplicates.any()):
        raise ValueError("manifest contains duplicate video_path rows")

    labels = manifest["label"].astype(str)
    try:
        train_val, test = train_test_split(
            manifest,
            test_size=test_size,
            random_state=seed,
            stratify=labels,
        )
        val_relative = val_size / (1.0 - test_size)
        train, val = train_test_split(
            train_val,
            test_size=val_relative,
            random_state=seed + 1,
            stratify=train_val["label"].astype(str),
        )
    except ValueError as exc:
        raise ValueError(
            "could not build a stratified video-level split: every class "
            "needs enough clips for both sides of each split. Lower "
            "val_size/test_size or add more clips."
        ) from exc

    splits = {"train.json": train, "val.json": val, "test.json": test}
    output_dir.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for filename, frame in splits.items():
        clips = [_clip_dict(row) for _, row in frame.iterrows()]
        _write_split(output_dir / filename, filename[: filename.index(".")], clips)
        counts[filename[: filename.index(".")]] = len(clips)
    return SplitResult(counts=counts, output_dir=output_dir)


def load_split(path: Path) -> list[dict[str, Any]]:
    """Read a split JSON back into its clip list."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    return list(payload["clips"])


def _clip_dict(row: pd.Series) -> dict[str, Any]:
    clip: dict[str, Any] = {col: row[col] for col in MANIFEST_COLUMNS}
    clip["label"] = str(row["label"])
    return clip


def _write_split(path: Path, name: str, clips: list[dict[str, Any]]) -> None:
    payload = {
        "version": SPLIT_VERSION,
        "description": f"{name} split generated by safewatch.data.split",
        "clips": clips,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


__all__ = [
    "SPLIT_FILES",
    "SPLIT_VERSION",
    "SplitResult",
    "load_split",
    "split_manifest",
]
